switch to mac

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -24,17 +24,18 @@ install:
   #############################################################################
   # CMAKE                                                                     #
   #############################################################################
-  - export PATH=$CMAKE_ROOT/bin:$PATH
-  - CMAKE_33_FOUND=$(cmake --version | grep " 3\.3\." >/dev/null && { echo 0; } || { echo 1; })
-  - if [ $CMAKE_33_FOUND -ne 0 ]; then
-      mkdir -p $CMAKE_ROOT &&
-      cd $CMAKE_ROOT &&
-      travis_retry wget --no-check-certificate http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz &&
-      tar -xzf cmake-3.3.2-Linux-x86_64.tar.gz &&
-      mv cmake-3.3.2-Linux-x86_64/* . &&
-      rm -rf cmake-3.3.2-Linux-x86_64.tar.gz cmake-3.3.2-Linux-x86_64 &&
-      cd -;
-    fi
+  #- export PATH=$CMAKE_ROOT/bin:$PATH
+  #- CMAKE_33_FOUND=$(cmake --version | grep " 3\.3\." >/dev/null && { echo 0; } || { echo 1; })
+  #- if [ $CMAKE_33_FOUND -ne 0 ]; then
+  #    mkdir -p $CMAKE_ROOT &&
+  #    cd $CMAKE_ROOT &&
+  #    travis_retry wget --no-check-certificate http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz &&
+  #    tar -xzf cmake-3.3.2-Linux-x86_64.tar.gz &&
+  #    mv cmake-3.3.2-Linux-x86_64/* . &&
+  #    rm -rf cmake-3.3.2-Linux-x86_64.tar.gz cmake-3.3.2-Linux-x86_64 &&
+  #    cd -;
+  #  fi
+  - brew install cmake
   - cmake --version
   #############################################################################
   # BOOST                                                                     #
